% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 'createVTKstruct' returns an empty 'VTKstruct', i.e., a Matlab structure
% suitable for storing the information extracted from a .VTK file
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function VTKstruct = createVTKstruct

%% CREATE THE 'VTKstruct'  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
VTKstruct = struct ('Dataset', [], ...
    'NumPoints', [], ...
    'Points', [], ...
    'NumCells', [], ...
    'Cells', [], ...
    'PointData', [], ...
    'CellData', [], ...
    'Field', [], ...
    'CellTypes', [], ...
    'FilePath', []);